/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["hello_api_hello_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Board */
        get: operations["board_api_board_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mapping */
        post: operations["mapping_api_mapping_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/adjust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Adjust */
        post: operations["adjust_api_adjust_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hint */
        get: operations["hint__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustIn */
        AdjustIn: {
            /**
             * Type
             * @enum {string}
             */
            type: "value" | "exclude" | "target";
            /** Reason */
            reason: string;
            /** Player */
            player?: string | null;
            /** Player Id */
            player_id?: number | null;
            /** Factor */
            factor?: number | null;
            /** Class */
            class?: string | null;
            /** Count */
            count?: number | null;
        };
        /** AdjustResult */
        AdjustResult: {
            /** Described */
            described: string;
            /** Count */
            count: number;
            /** Player Id */
            player_id: number | null;
            board: components["schemas"]["BoardPayload"];
        };
        /** BandOut */
        BandOut: {
            /** P25 */
            p25: number;
            /** P50 */
            p50: number;
            /** P75 */
            p75: number;
        };
        /** BidderOut */
        BidderOut: {
            /** Team Id */
            team_id: number;
            /** Label */
            label: string;
            /** Nick */
            nick: string | null;
            /**
             * Intent
             * @enum {string}
             */
            intent: "keen" | "neutral" | "reluctant";
            /** Credits */
            credits: number;
            /** Depth */
            depth: number;
            /** Overpay */
            overpay: number;
            /** Ceiling */
            ceiling: number;
            /** Reasons */
            reasons: string[];
        };
        /** BlockOut */
        BlockOut: {
            /** Classic Role */
            classic_role: string;
            /** Classes */
            classes: string[];
        };
        /** BoardPayload */
        BoardPayload: {
            /** Run Id */
            run_id: string;
            /** Scenario */
            scenario: string;
            settings: components["schemas"]["SettingsOut"];
            /** League Conflicts */
            league_conflicts: string[];
            /** Problems */
            problems: string[];
            /** Status */
            status: string | null;
            /** Locked */
            locked: boolean | null;
            /** Picks */
            picks: number;
            me: components["schemas"]["LedgerOut"];
            /** Teams */
            teams: components["schemas"]["LedgerOut"][];
            /** Market Credits */
            market_credits: number;
            /** Inflation */
            inflation: number;
            /** Composition */
            composition: {
                [key: string]: number;
            };
            /** Credits By Class */
            credits_by_class: {
                [key: string]: number;
            };
            /**
             * Modules
             * @default []
             */
            modules: string[];
            /**
             * Role Demand
             * @default {}
             */
            role_demand: {
                [key: string]: number[];
            };
            /**
             * My Coverage
             * @default {}
             */
            my_coverage: {
                [key: string]: number;
            };
            /**
             * Module Demand
             * @default {}
             */
            module_demand: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /**
             * My Squad
             * @default []
             */
            my_squad: components["schemas"]["SquadMemberOut"][];
            /**
             * Room By Class
             * @default {}
             */
            room_by_class: {
                [key: string]: number;
            };
            /**
             * Occupancy
             * @default {}
             */
            occupancy: {
                [key: string]: number;
            };
            /**
             * Pins
             * @default {}
             */
            pins: {
                [key: string]: string;
            };
            block?: components["schemas"]["BlockOut"] | null;
            /** Player List Hash */
            player_list_hash?: string | null;
            /** Reserve */
            reserve: number;
            /** Budget */
            budget: number;
            /** Slot Price */
            slot_price: number;
            /** Targets Departed */
            targets_departed: string[];
            /** Completion Value */
            completion_value: number | null;
            /** Selected */
            selected: number | null;
            lot: components["schemas"]["LotOut"] | null;
            lot_pressure: components["schemas"]["PressureOut"] | null;
            adjustments: components["schemas"]["LayerOut"];
            /** Prices */
            prices: {
                [key: string]: components["schemas"]["PriceRowOut"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HelloPayload */
        HelloPayload: {
            /**
             * Phase
             * @enum {string}
             */
            phase: "pending" | "live";
            /**
             * Mode
             * @enum {string}
             */
            mode: "feed" | "replay" | "state";
            /** Session Code */
            session_code: string | null;
            /** Feed */
            feed: string;
            /** Run */
            run: string;
            /** Scenario */
            scenario: string | null;
            settings: components["schemas"]["SettingsOut"] | null;
            /** League Conflicts */
            league_conflicts: string[];
            /** Note */
            note: string | null;
            /** Teams */
            teams: components["schemas"]["TeamOut"][];
            /** Participants */
            participants: string[];
            mapping: components["schemas"]["MappingOut"] | null;
            board: components["schemas"]["BoardPayload"] | null;
        };
        /** LayerOut */
        LayerOut: {
            /** Count */
            count: number;
            /** Applied */
            applied: number;
            /** Value Factor */
            value_factor: {
                [key: string]: number;
            };
            /** Excluded */
            excluded: number[];
            /** Targets */
            targets: {
                [key: string]: number;
            };
            /** Problems */
            problems: string[];
            /** Sha256 */
            sha256: string;
        };
        /** LedgerOut */
        LedgerOut: {
            /** Team Id */
            team_id: number;
            /** Label */
            label: string;
            /** Nick */
            nick: string | null;
            /** Budget */
            budget: number;
            /** Spent */
            spent: number;
            /** Credits */
            credits: number;
            /** Picks */
            picks: number[];
            /** Goalkeepers */
            goalkeepers: number;
            /** Outfield */
            outfield: number;
            /** Unknown */
            unknown: number;
            /** Missing Goalkeepers */
            missing_goalkeepers: number;
            /** Missing Outfield */
            missing_outfield: number;
            /** Open Slots */
            open_slots: number;
            /**
             * Classic
             * @default {}
             */
            classic: {
                [key: string]: number;
            };
        };
        /** LotOut */
        LotOut: {
            /** Player Id */
            player_id: number;
            /** Name */
            name: string;
            /** Team Short */
            team_short: string;
            /** Role Class */
            role_class: string;
            /** Roles */
            roles: string[];
            /** Tier */
            tier: number;
            band: components["schemas"]["BandOut"] | null;
            /** Expected Price */
            expected_price: number | null;
            /** Sold To */
            sold_to: number | null;
            /**
             * Fvm
             * @default 0
             */
            fvm: number;
            /**
             * Apps
             * @default 0
             */
            apps: number;
        };
        /** MappingIn */
        MappingIn: {
            /** Mine */
            mine: number;
            /** Nicks */
            nicks?: {
                [key: string]: string;
            };
        };
        /** MappingOut */
        MappingOut: {
            /** Mine */
            mine: number;
            /** Nicks */
            nicks: {
                [key: string]: string;
            };
        };
        /** PressureOut */
        PressureOut: {
            /** Player Id */
            player_id: number;
            /** Expected */
            expected: number;
            /** Estimate */
            estimate: number;
            /** Bidders */
            bidders: components["schemas"]["BidderOut"][];
        };
        /** PriceRowOut */
        PriceRowOut: {
            /** Player Id */
            player_id: number;
            /** Name */
            name: string;
            /** Team Short */
            team_short: string;
            /** Role Class */
            role_class: string;
            /** Roles */
            roles: string[];
            /** Tier */
            tier: number;
            band: components["schemas"]["BandOut"];
            /** Expected Price */
            expected_price: number;
            /** Value P50 */
            value_p50: number;
            /**
             * Fvm
             * @default 0
             */
            fvm: number;
            /**
             * Apps
             * @default 0
             */
            apps: number;
            pressure?: components["schemas"]["PressureOut"] | null;
        };
        /** RefreshResult */
        RefreshResult: {
            board: components["schemas"]["BoardPayload"];
            /** Problems */
            problems: string[];
        };
        /** SettingsOut */
        SettingsOut: {
            /** Budget */
            budget: number;
            /** Goalkeepers */
            goalkeepers: number[];
            /** Outfield */
            outfield: number[];
            /** Size */
            size: number[];
            /** Game */
            game: number;
            /** Team Count */
            team_count: number;
            /**
             * Source
             * @enum {string}
             */
            source: "session" | "league";
            /**
             * Classic Buckets
             * @default {}
             */
            classic_buckets: {
                [key: string]: number[];
            };
        };
        /** SquadMemberOut */
        SquadMemberOut: {
            /** Player Id */
            player_id: number;
            /** Name */
            name: string;
            /** Team Short */
            team_short: string;
            /** Roles */
            roles: string[];
            /** Role Class */
            role_class: string;
        };
        /** TeamOut */
        TeamOut: {
            /** Team Id */
            team_id: number;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hello_api_hello_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloPayload"];
                };
            };
        };
    };
    board_api_board_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPayload"];
                };
            };
        };
    };
    mapping_api_mapping_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adjust_api_adjust_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdjustResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResult"];
                };
            };
        };
    };
    hint__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
