"""The weekly forecast (spec, "`fanta-manager` -- the weekly loop").

3a's `analysis/weekly.py`, split by concern in 3b: `rounds` (the round and
its deadlines), `forecast` (the rows), `xi` (the solve), `records` (the
immutable write), `report` (the facade), `notes` (the override file), `blend`
(p_start by precedence, and the checks), `config` (the weekly layer's own
constants and hash). Every public name is re-exported here so callers keep
their import path.
"""

from fantaclaude.analysis.weekly.blend import (
    EMPTY_BLEND,
    SOURCE_NOTE,
    SOURCE_PUBLISHED,
    SOURCE_SQUALIFICATO,
    Blended,
    BlendLayer,
    blend,
    load_layer,
)
from fantaclaude.analysis.weekly.config import (
    DEFAULT_CONFIG,
    WEEKLY_VERSION,
    WeeklyConfig,
    weekly_hash,
)
from fantaclaude.analysis.weekly.errors import ForecastError, LateForecast
from fantaclaude.analysis.weekly.forecast import (
    Forecast,
    ForecastRow,
    Terms,
    forecast,
    load_terms,
    newest_probabili_file,
    scoring_in_force,
)
from fantaclaude.analysis.weekly.notes import (
    EMPTY_NOTES,
    FACTOR_RANGE,
    HEADER,
    KEYS,
    KINDS,
    LineupNote,
    LineupNotesError,
    NotesLayer,
    ResolvedNote,
    append_lineup_note,
    load_lineup_notes,
    note_from_entry,
    parse_lineup_notes,
    render_note,
    resolve_notes,
)
from fantaclaude.analysis.weekly.records import export_lineup_records, write_lineup_run
from fantaclaude.analysis.weekly.report import TOP_PER_ROLE, LineupReport, lineup
from fantaclaude.analysis.weekly.rounds import (
    MATCHDAY_READ_WINDOW,
    STALE_COMPILATION,
    PlayerFixture,
    Round,
    compilation_staleness,
    matchday_cross_check,
    player_fixtures,
    target_round,
    uncompiled_match_warning,
)
from fantaclaude.analysis.weekly.xi import (
    ADAPTED_MALUS,
    Bench,
    BenchEntry,
    CloseCall,
    Contingency,
    RosterPlayer,
    XiChoice,
    XiSlot,
    choose_xi,
    close_calls,
    contingencies,
    my_roster,
    order_bench,
)

__all__ = [
    "ADAPTED_MALUS",
    "DEFAULT_CONFIG",
    "EMPTY_BLEND",
    "EMPTY_NOTES",
    "FACTOR_RANGE",
    "HEADER",
    "KEYS",
    "KINDS",
    "MATCHDAY_READ_WINDOW",
    "SOURCE_NOTE",
    "SOURCE_PUBLISHED",
    "SOURCE_SQUALIFICATO",
    "STALE_COMPILATION",
    "TOP_PER_ROLE",
    "WEEKLY_VERSION",
    "Bench",
    "BenchEntry",
    "BlendLayer",
    "Blended",
    "CloseCall",
    "Contingency",
    "Forecast",
    "ForecastError",
    "ForecastRow",
    "LateForecast",
    "LineupNote",
    "LineupNotesError",
    "LineupReport",
    "NotesLayer",
    "PlayerFixture",
    "ResolvedNote",
    "RosterPlayer",
    "Round",
    "Terms",
    "WeeklyConfig",
    "XiChoice",
    "XiSlot",
    "append_lineup_note",
    "blend",
    "choose_xi",
    "close_calls",
    "compilation_staleness",
    "contingencies",
    "export_lineup_records",
    "forecast",
    "lineup",
    "load_layer",
    "load_lineup_notes",
    "load_terms",
    "matchday_cross_check",
    "my_roster",
    "newest_probabili_file",
    "note_from_entry",
    "order_bench",
    "parse_lineup_notes",
    "player_fixtures",
    "render_note",
    "resolve_notes",
    "scoring_in_force",
    "target_round",
    "uncompiled_match_warning",
    "weekly_hash",
    "write_lineup_run",
]
